#!/bin/bash

# This script exports the quizzes as JSON.

MONGO_USER="quiz"
MONGO_PASSWORD="password"

kubectl exec $(kubectl get po -o name -l deployment=mongodb) -- mongoexport -u $MONGO_USER -p $MONGO_PASSWORD -d kahootDB -c kahootGames --quiet
